# Generated by Django 3.0.3 on 2021-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('buisness_name', models.CharField(max_length=50)),
                ('person_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('verified_status', models.CharField(choices=[('verified', 'Verified'), ('notverified', 'Notverified')], default='notverified', max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
