# Generated by Django 3.0.3 on 2021-05-18 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 6, 52, 7, 966835, tzinfo=utc)),
        ),
    ]
